#!/usr/bin/bash

install-aws-cli latest
install-node latest
install-yarn latest
install-amplify-cli latest
install-python 3
install-ruby 3.1.2

function fail {
    echo $* 1>&2
    echo *** FAILED ***
    exit 1
}

. ~/.nvm/nvm.sh
. ~/.rvm/scripts/rvm

. ~/.bashrc
. ~/.profile


for COMM in aws node yarn python3 amplify ruby
do
    type $COMM || fail $COMM failed to install
done

echo *** PASSED ***