#!/usr/bin/bash

export ENV_AWS_CLI_VERSION=latest
export ENV_NODE_VERSION=latest
export ENV_YARN_VERSION=latest
export ENV_PYTHON_VERSION=latest
export ENV_AMPLIFY_CLI_VERSION=latest
export ENV_RUBY_VERSION=3.1.2

env-install

function fail {
    echo $* 1>&2
    echo *** FAILED ***
    exit 1
}

. ~/.nvm/nvm.sh
. ~/.rvm/scripts/rvm

. ~/.bashrc
. ~/.profile


for COMM in aws node yarn python3 amplify ruby
do
    type $COMM || fail $COMM failed to install
done

echo *** PASSED ***